/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HighScore = IDL.Record({
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getHighScores' : IDL.Func([], [IDL.Vec(HighScore)], ['query']),
  'submitHighScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HighScore = IDL.Record({ 'score' : IDL.Nat, 'playerName' : IDL.Text });
  
  return IDL.Service({
    'getHighScores' : IDL.Func([], [IDL.Vec(HighScore)], ['query']),
    'submitHighScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };